apiVersion: apps/v1
kind: Deployment
metadata:
   name: blockchain-deployment
   namespace: default
spec:
   replicas: 1
   selector:
      matchLabels:
         bb: web
   template:
      metadata:
         labels:
            bb: web
      spec:
         containers:
            -  name: blockchain-container
               image: blockchain:v3
               imagePullPolicy: Never
               env:
               -  name: PORT
                  value: "3000"
               readinessProbe:
                  httpGet:
                     path: /
                     port: 3000
                  initialDelaySeconds: 2
                  periodSeconds: 2
                  timeoutSeconds: 1
                  successThreshold: 1
                  failureThreshold: 10
               resources:
                  limits:
                     memory: 200Mi
                  requests:
                     cpu: 200m
                     memory: 200Mi
            #Adding same container to test things
            -  name: blockchain-container2
               image: blockchain:v3
               imagePullPolicy: Never
               env:
               -  name: PORT
                  value: "3001"
               readinessProbe:
                  httpGet:
                     path: /
                     port: 3001
                  initialDelaySeconds: 2
                  periodSeconds: 2
                  timeoutSeconds: 1
                  successThreshold: 1
                  failureThreshold: 10
               resources:
                  limits:
                     memory: 200Mi
                  requests:
                     cpu: 200m
                     memory: 200Mi
---
apiVersion: v1
kind: Service
metadata:
   name: blockchain-service
   namespace: default
spec:
   type: NodePort
   selector:
      bb: web
   ports:
      - port: 3000
        targetPort: 3000
        nodePort: 30001
        name: container-1
      - port: 3001
        targetPort: 3001
        nodePort: 30002
        name: container-2